### ISSUE TITLE
Use Ensaio to fetch the tutorial data

### ISSUE THREAD

**Issue by leouieda** [fatiando/tutorials#2]
The [gravity processing tutorial](https://github.com/fatiando/tutorials/blob/main/gravity-processing.ipynb) uses Pooch to fetch the datasets from the Zenodo archives at the start of the tutorial. This is good to showcase Pooch but we now have Ensaio for this. It would be good to start using it in the tutorial so we can test it out. 

A compromise between using Ensaio and showcasing Pooch would be to:

1. Use Ensaio to fetch some of the data. We load Southern Africa gravity, Earth topography, and Earth geoid. We could just get the topography and geoid with Ensaio for example.
2. Say that Ensaio uses Pooch under the hood and that, for example, you could load the Africa gravity data with Pooch as well. The text can mention `ensaio.fetch_southern_africa_gravity` and then show how to use `pooch.retrieve` to achieve the same thing. 

Or maybe we don't do this at all and just use Ensaio. We can then make a separate short tutorial just for Pooch.

Any thoughts/preferences on one of these options or **volunteers to implement the change** would be much appreciated ❤️

**Comment by MGomezN** [comment]
> Any thoughts/preferences on one of these options or **volunteers to implement the change** would be much appreciated ❤️
I volunteer to do this.

In my opinion, as a Python beginner, I would prefer to explain that there are three ways to "Fetch the gravity and topography data" for this tutorial:
Using only Pooch (and insert a cell with the instructions)
Using only Ensaio (and insert a cell with the instructions)
Using both Pooch and Ensaio (and insert a cell with the instructions)

The problem is that there will be a large redundant block and that once the data is downloaded, the other options would not really do anything anymore, right? Maybe then leave the multiple options as markdown, and in case people need them, they can copy and paste.

**Comment by leouieda** [comment]
@MGomezN I like that idea and thanks for volunteering! How about having first a cell using Ensaio since that's the canonical way. Then have a section explaining that this could be done with Pooch to fetch any dataset (from the Zenodo DOI). The download would happen twice since the cache folder for Ensaio and `pooch.retrieve` are different by default. But since these are tiny data, it shouldn't be a problem. 

Alternatively, you could leave it as Markdown to avoid the second download as well. That's probably the better way to do this.
